server:
  port: 9999

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 최대 파일 크기 설정
      max-request-size: 10MB  # 최대 요청 크기 설정

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.project.user.dto

file:
  location: /Users/sujeong/Documents/project/upload
